# Generated by Django 4.1.4 on 2023-01-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('sandwiches', '0003_sandwich_sandwiches_delete_newspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
