# Generated by Django 4.1.4 on 2022-12-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sandwich', models.CharField(choices=[('oldCheeseSandwich', 'Old cheese sandwich'), ('youngCheeseSandwich', 'Young cheese sandwich'), ('humusSandwich', 'Humus sandwich')], max_length=255)),
                ('bread_type', models.CharField(choices=[('brown', 'Brown'), ('white', 'White')], max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
