# Generated by Django 4.1.4 on 2023-01-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0004_sandwich_image'),
        ('api', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sandwich',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sandwiches.sandwich'),
        ),
    ]
